server:
 port: 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
   gateway:
    routes:
        - id: EMPLOYEE-SERVICE-v1
          uri: lb://EMPLOYEE-SERVICE
          predicates:
           - Path= /employees/**   
           - Query= src,mobile
        - id: EMPLOYEE-SERVICE-V2.0
          uri: lb://EMPLOYEE-SERVICE-V2
          predicates:
           - Path= /employees/**  
           - Method= POST,GET 
           - Host= localhost*
          filters:
           - name: CircuitBreaker
             args:
              name: EMPLOYEE-SERVICE-V2.0
              fallbackuri: forward:/empServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
           - Path= /department/**    
          filters:
           - name: CircuitBreaker
             args:
              name: DEPARTMENT-SERVICE
              fallbackuri: forward:/deptServiceFallBack
#hystrix:
# command:
#  fallbackcmd:
#   execution:
#    isolation:
#     thread:
#      timeoutInMilliseconds: 5000     
      
management:
 endpoints:
  web:
   exposure:
    include:  hystrix.stream 
           
      
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
 service-url:
  defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost
  
   